/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUtilisateursRouteImport } from './routes/_app.utilisateurs'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppRhRouteImport } from './routes/_app.rh'
import { Route as AppReclamationsRouteImport } from './routes/_app.reclamations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppConfigurationIaRouteImport } from './routes/_app.configuration-ia'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppReclamationsRoute = AppReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationIaRoute = AppConfigurationIaRouteImport.update({
  id: '/configuration-ia',
  path: '/configuration-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AppAdmissionsRoute
  '/configuration-ia': typeof AppConfigurationIaRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/reclamations': typeof AppReclamationsRoute
  '/rh': typeof AppRhRoute
  '/tickets': typeof AppTicketsRoute
  '/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AppAdmissionsRoute
  '/configuration-ia': typeof AppConfigurationIaRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/reclamations': typeof AppReclamationsRoute
  '/rh': typeof AppRhRoute
  '/tickets': typeof AppTicketsRoute
  '/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admissions': typeof AppAdmissionsRoute
  '/_app/configuration-ia': typeof AppConfigurationIaRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/reclamations': typeof AppReclamationsRoute
  '/_app/rh': typeof AppRhRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/configuration-ia'
    | '/conversations'
    | '/dashboard'
    | '/reclamations'
    | '/rh'
    | '/tickets'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/configuration-ia'
    | '/conversations'
    | '/dashboard'
    | '/reclamations'
    | '/rh'
    | '/tickets'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admissions'
    | '/_app/configuration-ia'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/reclamations'
    | '/_app/rh'
    | '/_app/tickets'
    | '/_app/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rh': {
      id: '/_app/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reclamations': {
      id: '/_app/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof AppReclamationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuration-ia': {
      id: '/_app/configuration-ia'
      path: '/configuration-ia'
      fullPath: '/configuration-ia'
      preLoaderRoute: typeof AppConfigurationIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppConfigurationIaRoute: typeof AppConfigurationIaRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReclamationsRoute: typeof AppReclamationsRoute
  AppRhRoute: typeof AppRhRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppConfigurationIaRoute: AppConfigurationIaRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReclamationsRoute: AppReclamationsRoute,
  AppRhRoute: AppRhRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
